### ISSUE TITLE
Performance insights?

### ISSUE THREAD

**Issue by yannh** [qonto/prometheus-rds-exporter#187] opened 2024-06-13 08:44 UTC
Hello! Thanks for releasing this exporter :heart: I am looking for a prometheus exporter for RDS performance insights, is this something you ever considered of implementing, or maybe know of any solution for? Is this something that would be in scope for this project? Many thanks!

**Comment by vmercierfr** [comment] 2024-06-28 09:51
Hello,

Thanks for your interest in the project.

We don't plan to integrate RDS Performance Insights metrics in this exporter in the short term.

RDS performance insights metrics are available through Cloudwatch, I guess you may use the [Cloudwatch exporter](https://github.com/prometheus/cloudwatch_exporter) and specify the [DB_PERF_INSIGHTS metric math function](https://docs.aws.amazon.com/documentdb/latest/developerguide/performance-insights-cloudwatch.html).

We are using RDS Performance Insights console to identify the root cause of incidents and bottlenecks in RDS instances, but we don't have a plan for converting this information into actionable metrics/alerts.

For internal database metrics, we mostly rely on [Postgres exporter](https://github.com/prometheus-community/postgres_exporter) and custom internal catalog metrics using [SQL exporter](https://github.com/free/sql_exporter). If you are using PostgreSQL too, you may look at our configuration at https://qonto.github.io/database-monitoring-framework/latest/tutorials/postgresql/exporter-deployment.

**Comment by yannh** [comment] 2024-06-28 09:55
Hi @vmercierfr , thanks, I thought they were NOT published to cloudwatch... I mean "These metrics are published to CloudWatch only if there is load on the DB instance."  what on eartth :roll_eyes:  I ll follow up with our AWS team, if I can get them into cloudwatch it should be easy. Thanks, feel free to close if you don't plan on implementing!

**Comment by vmercierfr** [comment] 2024-06-28 12:04
Thanks, I'm closing the issue.

**Closed by vmercierfr** 2024-06-28 12:04 UTC
Labels: question
